[tool.poetry]
name = "class exercise 3"
version = "0.1.0"
description = ""
authors = ["koechian <ianovic8@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
